name: Build Desktop Jar
on: [push, workflow_dispatch] # Runs on every push or manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew desktop:dist --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mindustry-Lilypad
          path: desktop/build/libs/*.jar
